/**
 * @module cover-letter.model
 *
 * Cover-letter draft entity stored in `core.cover_letters`. Drafts are
 * generated by the LLM pipeline for high-scoring jobs (via the Phase 6
 * processing chain) and can be manually edited or regenerated from the
 * dashboard; regeneration never overwrites a draft the user has edited.
 */

/**
 * Cover-letter draft read model.
 */
export interface CoverLetter {
  /** Primary key. */
  readonly id: bigint;
  /** Job the draft was written for. */
  readonly jobId: bigint;
  /** Profile the draft was written for. */
  readonly profileId: number;
  /** Draft body in markdown. */
  readonly bodyMd: string;
  /** LLM provider/model snapshot used to generate the original draft. */
  readonly modelUsed: string | null;
  /** Whether the user has edited the draft since it was generated. */
  readonly edited: boolean;
  readonly createdAt: Date;
  readonly updatedAt: Date;
}
